# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediasources', '0004_auto_20170727_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='custom_thumbnail',
            field=models.ImageField(blank=True, help_text='You can use this field to change the thumbnail image shown for this video throughout the site. If this is not set, an image will automatically be retrieved from the video itself.', max_length=250, null=True, upload_to='uploads/media/customthumbnails/%Y/%m/%d'),
        ),
    ]
